[package]

name = "sc"
version = "0.1.0"
description = "Raw system calls"
repository = "https://github.com/kmcallister/syscall.rs"
readme = "README.md"
license = "MIT/Apache-2.0"

authors = [ "The syscall.rs Project Developers" ]
